### ISSUE TITLE
Is basemodel available on google drive?

### ISSUE THREAD

**Issue by mohwald** [hotosm/fAIr-utilities#26]
While creating docker, the basemodel is not now accessible either from link or using gdown:

```
STEP 27/29: RUN gdown --fuzzy https://drive.google.com/file/d/1wvJhkiOrSlHmmvJ0avkAdu9sslFf5_I0/view?usp=sharing
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1wvJhkiOrSlHmmvJ0avkAdu9sslFf5_I0

Error: building at STEP "RUN gdown --fuzzy https://drive.google.com/file/d/1wvJhkiOrSlHmmvJ0avkAdu9sslFf5_I0/view?usp=sharing": while running runtime: exit status 1
```

**Comment by kshitijrajsharma** [comment]
OOPSIE ! Mostly because I cleaned up my drive haha ! Will update it ! Thanks !

**Comment by kshitijrajsharma** [comment]
@omranlm  My drive is full , Can I ask you to create a shareable link ?

**Comment by omranlm** [comment]
@mohwald sorry for that, the RAMP base model is also available on https://github.com/radiantearth/model_ramp_baseline/tree/main/data/input 

However, I have also uploaded it in zip to a new google drive link 

`https://drive.google.com/file/d/1YQsY61S_rGfJ_f6kLQq4ouYE2l3iRe1k/view?usp=sharing`
